version: "3.9"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    command: start-dev --import-realm
    volumes:
      - ./testdata/kc-test-realm.json:/opt/keycloak/data/import/kc-test-realm.json:ro
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      - KC_DB=dev-mem
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
